title: "HydroConsulting â€“ Elisa"
description: "Consulenza idrologica, modellistica idraulica e pianificazione delle risorse idriche."

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: contrast

locale: "it"
markdown: kramdown

url: "https://ingelisacoraggio.github.io"
baseurl: "/hydroconsulting"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

masthead:
  nav: "main"
