title: "HydroConsulting â€“ Elisa"
description: "Consulenza idrologica, modellistica idraulica e pianificazione delle risorse idriche."

# Tema Minimal Mistakes compatibile con GitHub Pages
remote_theme: "mmistakes/minimal-mistakes"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default

locale: "it"
markdown: kramdown

url: "https://ingelisacoraggio.github.io"
baseurl: "/hydroconsulting"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

# Attiva il menu principale (fondamentale!)
masthead:
  nav: "main"
