title: "HydroConsulting â€“ Elisa"
description: "Consulenza idrologica, modellistica idraulica e pianificazione delle risorse idriche."

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: mint

locale: "it"
markdown: kramdown

url: "https://ingelisacoraggio.github.io"
baseurl: "/hydroconsulting"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

masthead:
  nav: "main"
