title: "HydroConsulting â€“ Elisa"
description: "Consulenza idrologica, modellistica idraulica e pianificazione delle risorse idriche."

minimal_mistakes_skin: default

locale: "it"
markdown: kramdown

url: "https://ingelisacoraggio.github.io"
baseurl: "/hydroconsulting"

plugins:
  - jekyll-include-cache

masthead:
  nav: "main"
